"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var superHeros = [];
// const heroPower: number[] = [];
var heroPower = [];
var allUsers = [];
// const MLModels: number[][] = [[255, 255, 255], "", []];
var MLModels = [[255, 255, 255], []];
superHeros.push("spiderman");
heroPower.push(2);
allUsers.push({ name: "", isActive: true });
